[package]
name = "parser"
version = "0.1.0"
authors = ["MTBorg <martinterneborg96@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
nom="*"
lalrpop-util = "0.17.2"
regex = "*"

[build-dependencies]
lalrpop = "0.17.2"
